"""
SecLog Analyzer Dashboard

This module provides a simple web dashboard to visualize security alerts.
It reads JSON output generated by the analyzer and displays it in a web interface.

Security Notes:
- Runs locally (localhost only)
- No user input is processed (safe by design)
- Debug mode should be disabled in production
"""

from flask import Flask, render_template
import json
import os
import re

app = Flask(__name__)


def build_timeline(logs):
    """
    Builds a chronological security timeline.
    """

    timeline = []

    for log in logs:
        timeline.append({
            "timestamp": log.get("timestamp"),
            "event": log.get("event"),
            "user": log.get("user"),
            "ip": log.get("ip")
        })

    return sorted(timeline, key=lambda x: x["timestamp"])


def load_json(file_path):
    """
    Safely loads JSON data from a file.

    Args:
        file_path (str): Path to JSON file

    Returns:
        list: Parsed JSON data or empty list if file not found
    """
    try:
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as file:
                return json.load(file)
        return []
    except Exception as e:
        print(f"[ERROR] Failed to load JSON: {e}")
        return []


def read_logs(file_path):
    """
    Reads raw log lines from a text log file.
    """

    try:
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as file:
                return file.readlines()
        return []
    except Exception as e:
        print(f"[ERROR] Failed to read log file: {e}")
        return []


def parse_log_line(log_line):
    """
    Parses a raw authentication log line into a structured dictionary.

    Expected format:
    YYYY-MM-DD HH:MM:SS EVENT user=USERNAME ip=IP_ADDRESS
    """

    pattern = r"(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (\w+) user=(\w+) ip=([\d\.]+)"
    match = re.match(pattern, log_line.strip())

    if match:
        return {
            "timestamp": match.group(1),
            "event": match.group(2),
            "user": match.group(3),
            "ip": match.group(4)
        }

    return {}


@app.route("/")
def index():
    """
    Main dashboard route.

    Loads all alert types and sends them to the template.
    """

    alerts = load_json("../output/alerts.json")
    critical_alerts = load_json("../output/critical_alerts.json")
    suspicious_alerts = load_json("../output/suspicious_alerts.json")
    off_hours_alerts = load_json("../output/off_hours_alerts.json")

    raw_logs = read_logs("../logs/example_auth.log")

    parsed_logs = []
    for log in raw_logs:
        clean_log = log.strip()

        # Skip empty lines and comments
        if not clean_log or clean_log.startswith("#"):
            continue

        parsed = parse_log_line(clean_log)
        if parsed:
            parsed_logs.append(parsed)

    timeline = build_timeline(parsed_logs)

    summary = {
        "LOW": 0,
        "MEDIUM": 0,
        "HIGH": 0,
        "CRITICAL": len(critical_alerts)
    }

    for alert in alerts:
        severity = alert.get("severity", "LOW")
        if severity in summary:
            summary[severity] += 1

    summary["HIGH"] += len(suspicious_alerts)
    summary["MEDIUM"] += len(off_hours_alerts)

    return render_template(
        "index.html",
        alerts=alerts,
        critical_alerts=critical_alerts,
        suspicious_alerts=suspicious_alerts,
        off_hours_alerts=off_hours_alerts,
        summary=summary,
        timeline=timeline
    )


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5000, debug=False)